window.SPR=function(){function z(a,d){var c=this;c.N=[];c.H=a||{};c.ud=b.Zc;c.ua=!1;c.Rc=d||b.Ac;p.vc(c.Rc);h.b(a[b.va]);a[b.f]=a[b.f]||q.current[b.f];a[b.url]=a[b.url]||f.na();a[b.title]||(a[b.title]=f.ma(a[b.url]));if(a[b.url])c.b=function(){if(c.Nc())return c.rc(),c;h[b.error](c.Xb());return null},c[b.bd]=function(a){c.Oc(a)?c.sc(a):c.Sb(a);return c},c[b.Uc]=function(a){c.Lc(a)?c.qc(a):c.Rb();return c},c[b.gd]=function(a){c.Pc(a)?c.tc(a):c.Tb();return c},c[b.Sc]=function(){c.ua||(c.w(c.ia(c.ia())),
c[b.La](100),c.ua=!0);return c},c[b.La]=function(a){if(e.contains(c.N,a))return null;if(e.contains(e.$,a)){var d=c.l();d[b.o]=b.Ma;d[b.Ma]=c.zb(a);c.w(d)}else h[b.error](b.Gb);return c},c.zb=function(a){var d,m=e.$,f={};if(!e.contains(m,a))h[b.error](b.xa);else if(!e.contains(c.N,a))for(d=0;d<m.length;d+=1){var l=m[d];a>=l&&!e.contains(c.N,l)&&(c.N.push(l),f[l]=!0,h[b.info](b.Fa+l))}return f},c.w=function(a){p.i(b.m,b.Wc,a)},c.rc=function(){c.w(c.Eb())},c.xd=function(){return q.current},c.l=function(){return v.fa(c.H)},
c.Eb=function(){var a=c.l();a[b.o]=b.Yc;return a},c.Nc=function(){var a;for(a=0;a<r.length;a+=1)if(!c.H[r[a]])return!1;return!0},c.Xb=function(){var a,d=[];for(a=0;a<r.length;a+=1)c.H[r[a]]||d.push(r[a]);return b.Ib+d.join(", ")},c.sc=function(a){c.w(c.Dc(a))},c.Oc=function(a){return a===b.ed||a===b.fd},c.Dc=function(a){var d=c.l();d[b.o]=b.cd;d[b.dd]=a;return d},c.Sb=function(a){if(a)h[b.error](a+b.Jb);else h[b.error](b.Jc)},c.ia=function(){var a=c.l();a[b.o]=b.Tc;return a},c.qc=function(a){c.w(c.ub(a))},
c.ub=function(a){var d=c.l();d[b.o]=b.Vc;d[b.$c]=a;return d},c.Lc=function(a){return!isNaN(a)},c.Rb=function(){h[b.error](b.Fb)},c.tc=function(a){c.w(c.Ec(a))},c.Ec=function(a){var d=c.l();d[b.o]=b.hd;d[b.ad]=a;return d},c.Pc=function(a){return!isNaN(a)&&c.Qc(a)},c.Qc=function(a){return e.hb(e.jd,a)},c.Tb=function(){h[b.error](b.Hb)};else h[b.error](b.ca+b.oa)}var b={m:"edge.simplereach.com",version:"2.18.1",fb:"d8rk54i4mohrb.cloudfront.net",global:"SPR",Db:"/n",Fc:"/t",Wc:"/v",pa:"/event",bb:"/pixel?bad=true&error=",
rd:"/iframe.html",gb:"/container.html",Ha:"000000000000000000000000",ca:"SPR-ERROR: ",oa:"100 - Missing url",ic:"__reach_config",Vb:"__memo_config",cb:"cache_buster",Da:"__srret",Ka:"__srui",R:"0",bc:"1",Cb:"img",cc:"1px",width:"width",g:"undefined",error:"error",Yb:"off",info:"info",K:"SPR_DEBUG",Ga:"//",da:"string",referrer:"referrer",uid:"uid",S:"callback",i:"jsonp",url:"url",title:"title",f:"pid",wa:"ignore_metadata",Wb:"meta",time:"time",mb:"datetime",c:"property",Mb:"itemprop",name:"name",
eb:"canonical",link:"link",rel:"rel",kd:"article",$b:"og:url",Ic:"twitter:url",Zb:"og:title",Hc:"twitter:title",Va:"article:published_at",Za:"article:sr_published_at",Wa:"article:published_time",lb:"datePublished",dc:"og:pubdate",Ca:"pubdate",Ta:"article:author",Xa:"article:sr_author",ea:"author",ab:"article:tag",$a:"article:sr_tag",Ua:"article:section",Ya:"article:sr_section",content:"content",href:"href",Ea:"s",r:"r",t:"t",e:"e",x:"x",n:"n",Kc:"v",va:"ignore_errors",hc:"preview",B:"authors",C:"channels",
L:"tags",h:"date",td:"inframe",Qa:"ajax",Bc:"social_tracking",qd:"iframe",jb:"custom_tracking",jc:"reach_tracking",v:"ref_url",Z:"page_url",Cd:"user_id",Ub:"manual_scroll_depth",ka:"content_height",wd:"rd",pd:"fb",ld:"de",ec:"pi",ib:"csd",fc:"partners-api.pinterest.com",gc:"/v1/urls/count.json",xa:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",Fa:"[info] sending scrollDepth of: ",pc:"[info] scroll depth not activated, not sending data",Ac:"SimplereachVideo",o:"event_name",
Ib:"Missing params please provide a ",Jb:" is not a valid start event type.",Jc:"Cannot have an undefined start type. Please provide a start type.",Fb:"Please pass a valid number",Gb:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",yd:"[error] Quartile for this video already sent",Hb:"Please pass a valid threshold number",Xc:"video_id",Qb:"length",description:"description",Bd:"thumbnail_url",zd:"source_url",Aa:"networks",Zc:"video",bd:"start",Uc:"elapsed",Sc:"complete",
La:"quartile",gd:"elapsedThreshold",Yc:"init",cd:"start",Vc:"elapsed",Ma:"quartile",Tc:"complete",hd:"elapsed_threshold",dd:"start_type",ed:"auto",fd:"click",$c:"seconds_elapsed",ad:"threshold"},e={nc:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},kb:function(a){for(var b=[],c=/-|\//,m=[/\d{4}\/\d{1,2}\/\d{1,2}/,/\d{4}-\d{1,2}-\d{1,2}/,/20\d{6}/],g=0;g<m.length;g++){var e=a.match(m[g]);if(null!=e)return a=e[0],a.match(c)?b=a.split(c):(b[0]=a.substring(0,4),b[1]=a.substring(4,
6),b[2]=a.substring(6,8)),new Date(b[0],b[1]-1,b[2])}},s:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){window.console&&console.log(a)},Lb:function(a){return"[object String]"===Object.prototype.toString.call(a)},P:function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},za:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b+
",")},hb:function(a,b){if(!isNaN(b)&&!this.Lb(b))for(var c=0;c<=a.length;c++)if(a[c]===b)return!0;return!1},V:function(a){typeof a===b.da&&(a=a.split(","));if(this.s(a)){for(var d=0;d<a.length;d+=1)typeof a[d]===b.da&&(a[d]=a[d].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},G:function(){},ra:function(){return window.location.protocol+"//"},$:[25,50,75,100],jd:[3,15,30,45]},t={encode:function(a,b){var c=[];if(e.s(a))for(var d=0,g;d<a.length;d+=1)g=a[d],/\[\]$/.test(b)?
c.push(encodeURIComponent(b)+"="+encodeURIComponent(g)):c.push(this.encode(g,b+"["+("object"===typeof g?d:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(b)+"="+encodeURIComponent(a));else for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(b?c.push(this.encode(a[d],b+"["+d+"]")):c.push(this.encode(a[d],d)));return c.join("&")},decode:function(a){var d={},c=0,m={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var g=
a[c].split("="),f=decodeURIComponent(g[0]),h=d,l=0,n=f.split("]["),k=n.length-1;/\[/.test(n[0])&&/\]$/.test(n[k])?(n[k]=n[k].replace(/\]$/,""),n=n.shift().split("[").concat(n),k=n.length-1):k=0;if(2===g.length)if(g=(g=decodeURIComponent(g[1]))&&!isNaN(g)?+g:g===b.g?void 0:void 0!==m[g]?m[g]:g,k)for(;l<=k;l+=1)f=""===n[l]?h.length:n[l],h=h[f]=l<k?h[f]||(n[l+1]&&isNaN(n[l+1])?{}:[]):g;else e.s(d[f])?d[f].push(g):d[f]=void 0!==d[f]?[d[f],g]:g;else f&&(d[f]=void 0)}return d}},u={Ba:{},ta:function(a){var b=
document.cookie||"",c=this.Ba[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.Ba[a]=c);return(a=b.match(c))&&decodeURIComponent(a[1])},ba:function(a,b,c){var d="";c&&(d="; expires="+c.toGMTString());document.cookie=a+"="+b+d+"; path=/"},md:function(a){this.ba(a,"",new Date(1982,5,13))}},q={current:{}},h={qa:!1,info:e.G,error:e.log,b:function(){window[b.K]&&(this.qa=!0,window[b.K][b.info]&&(this[b.info]=window[b.K][b.info]),window[b.K][b.error]&&
(this[b.error]=window[b.K][b.error]))},reset:function(){this.qa=!1;this[b.info]=e.G;this[b.info]=e.log},xc:function(a){var d=document.createElement(b.Cb);d.src=e.ra()+b.m+b.bb+a.message;d.setAttribute(b.width,b.cc);document.body?document.body.appendChild(d):document.head.appendChild(d)},yc:function(a){a===b.info?(this[b.info]=e.log,this[b.error]=e.log):a===b.error?(this[b.info]=e.G,this[b.error]=e.log):(this[b.info]=e.G,this[b.error]=e.G)}},f={R:0,F:{x:0,y:0},X:!0,b:function(){function a(){e.X=document[g]?
!1:!0}function d(){e.flush();window.removeEventListener("DOMContentLoaded",d,!1)}function c(){/loaded|interactive|complete/.test(document.readyState)&&(document.detachEvent("onreadystatechange",c),h&&(h=!1,e.flush()))}var e=this;e.R=0;this.ac(window,"mousemove",function(a){e.F={x:a.clientX,y:a.clientY}});if(typeof document.hidden!==b.g){var g="hidden";var f="visibilitychange"}else typeof document.mozHidden!==b.g?(g="mozHidden",f="mozvisibilitychange"):typeof document.msHidden!==b.g?(g="msHidden",
f="msvisibilitychange"):typeof document.webkitHidden!==b.g&&(g="webkitHidden",f="webkitvisibilitychange");typeof document.addEventListener!==b.g&&typeof g!==b.g&&document.addEventListener(f,a,!1);var h=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",d,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},Na:function(a,d){var c=document.createElement("iframe"),e=document.body;c.setAttribute("name","spr");c.src=a;c.setAttribute("height","1");c.setAttribute("width",
"1");c.setAttribute("visible","false");c.setAttribute("id","spr-iframe-"+d);c.style.display="none";e||(e=this.j("BODY")[0]);e||(e=this.j("HEAD")[0]);h[b.info](a);e.appendChild(c);return c},qb:function(){return this.a(this,b.c,b.$b)},ob:function(){return this.wb(this,b.eb)},rb:function(){return this.a(this,b.name,b.Ic)},sb:function(){return window.location.protocol+b.Ga+window.location.hostname+window.location.pathname},na:function(){var a=this.ob()||this.qb()||this.rb()||this.sb();return e.s(a)?a[0]:
a},pb:function(){var a=this.a(this,b.c,b.Za)||this.a(this,b.name,b.Ca)||this.a(this,b.c,b.Ca)||this.a(this,b.c,b.Va)||this.a(this,b.c,b.Wa)||this.a(this,b.c,b.dc)||this.xb(this,b.Mb,b.lb)||this.a(this,b.name,b.h);return e.s(a)?a[0]:a},nb:function(){return this.a(this,b.c,b.Xa)||this.a(this,b.c,b.Ta)||this.a(this,b.c,b.ea)||this.a(this,b.name,b.ea)},la:function(a,d){return this.a(this,b.c,a)||this.a(this,b.c,d)},sa:function(){return document.referrer},ma:function(a){a=this.a(this,b.c,b.Zb)||this.a(this,
b.name,b.Hc)||document.title||a||!1;return e.s(a)?a[0]:a},W:function(a,b,c,e,g){a=a.j(b);b=[];for(var d=0;d<a.length;d++)a[d].getAttribute(c)===e&&b.push(a[d].getAttribute(g));if(b.length)return 1==b.length?b[0]:b},wb:function(a,d){return this.W(a,b.link,b.rel,d,b.href)},a:function(a,d,c){return this.W(a,b.Wb,d,c,b.content)},xb:function(a,d,c){return this.W(a,b.time,d,c,b.mb)},kc:function(a){var b=document.body,c=this.j("BODY")[0],e=this.j("HEAD")[0];b&&b.contains(a)?b.removeChild(a):c&&c.contains(a)?
c.removeChild(a):e&&e.contains(a)&&e.removeChild(a);return a},Oa:function(a){var d=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id","spr-script");c.src=a;h[b.info](a);this.Y(function(){setTimeout(function(){d.j("HEAD")[0].appendChild(c)},1)});return c},u:[],ready:/loaded|interactive|complete/.test(document.readyState),flush:function(){var a=this.u.shift();for(this.ready=!0;a;)a(),a=this.u.shift()},Y:function(a){/loaded|interactive|complete/.test(document.readyState)?
(this.u.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function c(){if(!document.uniqueID&&document.expando)return this.u.push(a);try{document.documentElement.doScroll("left"),a()}catch(m){setTimeout(c,0)}}():this.u.push(a):this.u.push(a)},ac:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},Yb:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},O:function(){return(window.pageYOffset?
window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.R},j:function(a){var b=[],c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(document.getElementById(a.substring(1)));break;case ".":var g=document.getElementsByTagName("*");for(e=" "+a.substring(1)+" ";c<g.length;c+=1)a=(" "+g[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(e)&&b.push(g[c]);break;default:b=document.getElementsByTagName(a)}return b}},v={fa:function(a){var d;
var c=e.P(a);c[b.B]&&(c[b.B]=e.V(c[b.B]));c[b.C]&&(c[b.C]=e.V(c[b.C]));c[b.L]&&(c[b.L]=e.V(c[b.L]));c[b.h]&&typeof c[b.h]!==b.da&&(c[b.h]=c[b.h].toString());c[b.referrer]=""==c[b.v]?"":this.aa(c[b.referrer]);c[b.v]=this.aa(c[b.v]);c[b.Z]=c[b.Z]||window.location.toString();c[b.uid]?c[b.uid]=c[b.uid]:(d=this.Bb())&&(c[b.uid]=d);c[b.url]&&(c[b.url]=this.oc(c[b.url]),a[b.url]=c[b.url]);return c},aa:function(a){""!==a&&(a=a||f.sa());return a},Bb:function(){return u.ta(b.Ka)},oc:function(a){if(0===a.indexOf("http%253A")||
0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},p={callbacks:{},T:b.global,vc:function(a){this.T=a},i:function(a,d,c,h,g){h=h||function(){};g||(g="cb");var k="cb"+e.nc(),m=this;c[g]=this.T+".API.callbacks."+k;g=e.ra();"file://"===g&&(g="http://");c[b.Kc]=b.version;c=t.encode(c);var l=f.Oa(g+a+d+"?"+c);m.callbacks[k]=function(a){setTimeout(function(){l.parentNode&&l.parentNode.removeChild(l)},0);h(a);try{delete m.callbacks[k]}catch(D){m.callbacks[k]=
null}}}},w={vd:!1,od:!0,A:0,Ia:5E3,Gc:12E5,interval:null,reset:function(){f.R=f.O();window.clearInterval(this.interval)},track:function(a){var d=this,c;d.interval=setInterval(function(){f.X&&(d.A+=d.Ia);d.Ja()&&(d.A=0);c=e.P(a);c[b.t]=d.A;c[b.e]=d.Kb()?5E3:0;c[b.Ea]=f.O();0===c[b.f]&&(c[b.f]=b.Ha);f.X&&!d.Ja()&&d.Mc(c)&&0<c[b.e]&&(d.A=0,p.i(b.m,b.Fc,c));d.Ob=f.F.x;d.Pb=f.F.y;d.Nb=f.O()},d.Ia)},Kb:function(){return!0!==this.vb?this.vb=!0:this.Ob!==f.F.x||this.Pb!==f.F.y||this.Nb!==f.O()?!0:!1},Ja:function(){return this.A>=
this.Gc},Mc:function(a){return a[b.url]&&a[b.f]}},k=e.$,y={M:[],data:{},response:null,options:null,Ad:!1,b:function(a,d){this.reset();this.options=d;this.response=a;var c=this;f.Y(function(){c.height=c.yb();c.J||(c.J=function(){c.ga()});q.current[b.Ub]?c.lc():c.Pa()})},Pa:function(){typeof document.addEventListener!==b.g?document.addEventListener("scroll",this.J,!1):window.attachEvent("onscroll",this.J);this.ga()},lc:function(){typeof document.removeEventListener!==b.g?document.removeEventListener("scroll",
this.J,!1):window.detachEvent("onscroll",this.J)},ga:function(){var a=this.Ab()+Math.min(document.documentElement.clientHeight,window.innerHeight||0),b=0;a>=this.height?b=k[3]:b=a/this.height*100;97<=b?this.I(k[3]):b>=k[2]?this.I(k[2]):b>=k[1]?this.I(k[1]):b>=k[0]&&this.I(k[0])},yb:function(){if(q.current[b.ka])var a=q.current[b.ka];else{a=document.body;var d=document.documentElement;a=Math.max(a.scrollHeight,a.offsetHeight,d.clientHeight,d.scrollHeight,d.offsetHeight)}return a},Ab:function(){var a=
"CSS1Compat"===(document.compatMode||"");return void 0!==window.pageYOffset?window.pageYOffset:a?document.documentElement.scrollTop:document.body.scrollTop},I:function(a){this.data={};if(!e.contains(k,a))h[b.error](b.xa);else if(!e.contains(this.M,a))if(this.wc(a),this.response[b.ib])this.uc();else h[b.info](b.pc)},wc:function(a){var d;for(d=0;d<k.length;d+=1){var c=k[d];a>=c&&!e.contains(this.M,c)&&(this.M.push(c),this.data[c]=!0,h[b.info](b.Fa+c))}},H:function(){return e.za({event:"csd",sd:this.data},
this.options)},uc:function(){if(!this.response.error){var a=this.H();p.i(b.m,b.pa,a)}},reset:function(){this.M=[]}},A={Aa:[{name:b.ec,Ra:b.fc,Sa:b.gc,S:b.S}],mc:function(a,b){return{url:b}},Cc:function(a,d){return function(c){c={event:b.Ea,url:a.url,cid:a.id,pid:a.pid,sn:a.name,data:c};e.za(c,d);p.i(b.m,b.pa,c)}},D:function(a,b){for(var c=this.Aa,d,g=0;g<c.length;g+=1){d=c[g];var f=e.P(a);f.name=d.name;a[d.name]&&p.i(d.Ra,d.Sa,this.mc(d.name,f.url),this.Cc(f,b),d.S)}}},B={track:function(a){var d=
this;0===a[b.f]&&(a[b.f]=b.Ha);p.i(b.m,b.Db,a,function(c){y.b(c,a);if(c.error)h[b.error](b.ca+c.error.code+" - "+c.error.message);else c.uid&&d.zc(c.uid),!1!==a[b.Bc]&&A.D(c,a)})},zc:function(a){u.ba(b.Ka,a,new Date(2042,5,13))}},x={nd:{},U:{},ha:!1,b:function(){try{f.b();var a=window[b.Vb]||window[b.ic];u.ta(b.Da)?this.ya=!0:this.ya=!1;u.ba(b.Da,b.bc,new Date(2042,5,13));this.D(a)}catch(d){f.Y(function(){h.xc(d)})}},D:function(a){if(a){var d;q.current=a;this.U=e.P(q.current);this.U[b.r]=this.ya;
(d=this.U[b.Qa]&&this.ha)||(a[b.url]=a[b.url]||f.na());if(a[b.url])h.b(a[b.va]),d&&(a.hasOwnProperty(b.wa)||(a[b.wa]=!0),a[b.Z]=a[b.v]=a[b.referrer]=a.url),a[b.title]||(a[b.title]=f.ma(a[b.url])),a[b.h]||(a[b.h]=f.pb()||e.kb(a[b.url])),a[b.L]||(a[b.L]=f.la(b.$a,b.ab)),a[b.C]||(a[b.C]=f.la(b.Ya,b.Ua)),a[b.B]||(a[b.B]=f.nb()),w.reset(),d=v.fa(a),d[b.hc]||(!1!==a[b.jc]&&(B.track(d),w.track(d)),!1!==a[b.jb]&&this.tb(d)),this.ha=!0;else h[b.error](b.ca+b.oa)}else h[b.error]("Params not passed to collect")},
tb:function(a){a[b.referrer]=a[b.referrer]||f.sa();a[b.v]=v.aa(a[b.v]);a[b.cb]=(new Date).getTime();a=t.encode(a);this.ja&&f.kc(this.ja);this.ja=f.Na(b.Ga+b.fb+b.gb+"?"+a,b.x)}},r=[b.f,b.Xc,b.Qb,b.h],C={create:function(a,b){return new z(a,b)},b:function(a,b){return this.create(a,b).b()}};return{Reach:{collect:function(a){x.D(a)}},QS:{decode:t.decode},debug:h,setLogLevel:function(a){h.yc(a)},API:p,collect:function(a){x.D(a)},decode:t.decode,init:function(){x.b()},iframeCollect:function(){},stop:function(){w.reset()},
scrollDepthReached:function(a){y.I(a)},video:function(a){return C.b(a,p.T)}}}();window.SPR.init();
