window.SimplereachVideo=function(){function v(a,d){var c=this;c.w=[];c.F=a||{};c.wc=b.Hb;c.R=!1;c.zb=d||b.kb;t.gb(c.zb);g.j(a[b.Aa]);a[b.v]=a[b.v]||u.current[b.v];a[b.url]=a[b.url]||r.qa();a[b.title]||(a[b.title]=r.oa(a[b.url]));if(a[b.url])c.j=function(){if(c.vb())return c.cb(),c;g[b.error](c.Ra());return null},c[b.Kb]=function(a){c.wb(a)?c.eb(a):c.Oa(a);return c},c[b.Cb]=function(a){c.ub(a)?c.bb(a):c.Na();return c},c[b.Pb]=function(a){c.xb(a)?c.fb(a):c.Pa();return c},c[b.Ab]=function(){c.R||(c.o(c.M(c.M())),
c[b.Y](100),c.R=!0);return c},c[b.Y]=function(a){if(e.contains(c.w,a))return null;if(e.contains(e.W,a)){var d=c.g();d[b.i]=b.Z;d[b.Z]=c.wa(a);c.o(d)}else g[b.error](b.Ea);return c},c.wa=function(a){var d,h=e.W,p={};if(!e.contains(h,a))g[b.error](b.Fa);else if(!e.contains(c.w,a))for(d=0;d<h.length;d+=1){var k=h[d];a>=k&&!e.contains(c.w,k)&&(c.w.push(k),p[k]=!0,g[b.info](b.ab+k))}return p},c.o=function(a){t.S(b.N,b.Eb,a)},c.cb=function(){c.o(c.Ca())},c.Ec=function(){return u.current},c.g=function(){return w.ga(c.F)},
c.Ca=function(){var a=c.g();a[b.i]=b.Gb;return a},c.vb=function(){var a;for(a=0;a<q.length;a+=1)if(!c.F[q[a]])return!1;return!0},c.Ra=function(){var a,d=[];for(a=0;a<q.length;a+=1)c.F[q[a]]||d.push(q[a]);return b.Ha+d.join(", ")},c.eb=function(a){c.o(c.nb(a))},c.wb=function(a){return a===b.Nb||a===b.Ob},c.nb=function(a){var d=c.g();d[b.i]=b.Lb;d[b.Mb]=a;return d},c.Oa=function(a){if(a)g[b.error](a+b.Ia);else g[b.error](b.rb)},c.M=function(){var a=c.g();a[b.i]=b.Bb;return a},c.bb=function(a){c.o(c.sa(a))},
c.sa=function(a){var d=c.g();d[b.i]=b.Db;d[b.Ib]=a;return d},c.ub=function(a){return!isNaN(a)},c.Na=function(){g[b.error](b.Da)},c.fb=function(a){c.o(c.ob(a))},c.ob=function(a){var d=c.g();d[b.i]=b.Qb;d[b.Jb]=a;return d},c.xb=function(a){return!isNaN(a)&&c.yb(a)},c.yb=function(a){return e.ia(e.Rb,a)},c.Pa=function(){g[b.error](b.Ga)};else g[b.error](b.mb+b.ta)}var b={N:"edge.simplereach.com",version:"2.18.1",ac:"d8rk54i4mohrb.cloudfront.net",global:"SPR",rc:"/n",Rc:"/t",Eb:"/v",lc:"/event",fa:"/pixel?bad=true&error=",
oc:"/iframe.html",bc:"/container.html",Pc:"000000000000000000000000",mb:"SPR-ERROR: ",ta:"100 - Missing url",Dc:"__reach_config",tc:"__memo_config",Zb:"cache_buster",Hc:"__srret",sb:"__srui",J:"0",xc:"1",Ba:"img",Xa:"1px",width:"width",c:"undefined",error:"error",Sa:"off",info:"info",u:"SPR_DEBUG",lb:"//",H:"string",referrer:"referrer",uid:"uid",$b:"callback",S:"jsonp",url:"url",title:"title",v:"pid",pc:"ignore_metadata",Qa:"meta",time:"time",la:"datetime",b:"property",La:"itemprop",name:"name",
ha:"canonical",link:"link",rel:"rel",Ub:"article",Ua:"og:url",qb:"twitter:url",Ta:"og:title",pb:"twitter:title",ba:"article:published_at",ea:"article:sr_published_at",ca:"article:published_time",ka:"datePublished",Ya:"og:pubdate",V:"pubdate",aa:"article:author",da:"article:sr_author",K:"author",Yb:"article:tag",Xb:"article:sr_tag",Vb:"article:section",Wb:"article:sr_section",content:"content",href:"href",Ic:"s",r:"r",t:"t",e:"e",x:"x",n:"n",tb:"v",Aa:"ignore_errors",Bc:"preview",A:"authors",B:"channels",
I:"tags",h:"date",qc:"inframe",Tb:"ajax",Nc:"social_tracking",nc:"iframe",ec:"custom_tracking",Fc:"reach_tracking",G:"ref_url",T:"page_url",Sc:"user_id",sc:"manual_scroll_depth",cc:"content_height",Cc:"rd",mc:"fb",gc:"de",yc:"pi",dc:"csd",zc:"partners-api.pinterest.com",Ac:"/v1/urls/count.json",Fa:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",ab:"[info] sending scrollDepth of: ",Jc:"[info] scroll depth not activated, not sending data",kb:"SimplereachVideo",i:"event_name",
Ha:"Missing params please provide a ",Ia:" is not a valid start event type.",rb:"Cannot have an undefined start type. Please provide a start type.",Da:"Please pass a valid number",Ea:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",Lc:"[error] Quartile for this video already sent",Ga:"Please pass a valid threshold number",Fb:"video_id",Ma:"length",description:"description",Qc:"thumbnail_url",Oc:"source_url",vc:"networks",Hb:"video",Kb:"start",Cb:"elapsed",Ab:"complete",
Y:"quartile",Pb:"elapsedThreshold",Gb:"init",Lb:"start",Db:"elapsed",Z:"quartile",Bb:"complete",Qb:"elapsed_threshold",Mb:"start_type",Nb:"auto",Ob:"click",Ib:"seconds_elapsed",Jb:"threshold"},e={Za:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},fc:function(a){for(var b=[],c=/-|\//,h=[/\d{4}\/\d{1,2}\/\d{1,2}/,/\d{4}-\d{1,2}-\d{1,2}/,/20\d{6}/],f=0;f<h.length;f++){var e=a.match(h[f]);if(null!=e)return a=e[0],a.match(c)?b=a.split(c):(b[0]=a.substring(0,4),b[1]=a.substring(4,6),
b[2]=a.substring(6,8)),new Date(b[0],b[1]-1,b[2])}},l:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){window.console&&console.log(a)},Ja:function(a){return"[object String]"===Object.prototype.toString.call(a)},jb:function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},uc:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b+",")},
ia:function(a,b){if(!isNaN(b)&&!this.Ja(b))for(var c=0;c<=a.length;c++)if(a[c]===b)return!0;return!1},C:function(a){typeof a===b.H&&(a=a.split(","));if(this.l(a)){for(var d=0;d<a.length;d+=1)typeof a[d]===b.H&&(a[d]=a[d].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},s:function(){},P:function(){return window.location.protocol+"//"},W:[25,50,75,100],Rb:[3,15,30,45]},x={encode:function(a,b){var c=[];if(e.l(a))for(var d=0,f;d<a.length;d+=1)f=a[d],/\[\]$/.test(b)?c.push(encodeURIComponent(b)+
"="+encodeURIComponent(f)):c.push(this.encode(f,b+"["+("object"===typeof f?d:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(b)+"="+encodeURIComponent(a));else for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(b?c.push(this.encode(a[d],b+"["+d+"]")):c.push(this.encode(a[d],d)));return c.join("&")},decode:function(a){var d={},c=0,h={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var f=a[c].split("="),m=decodeURIComponent(f[0]),
g=d,k=0,l=m.split("]["),n=l.length-1;/\[/.test(l[0])&&/\]$/.test(l[n])?(l[n]=l[n].replace(/\]$/,""),l=l.shift().split("[").concat(l),n=l.length-1):n=0;if(2===f.length)if(f=(f=decodeURIComponent(f[1]))&&!isNaN(f)?+f:f===b.c?void 0:void 0!==h[f]?h[f]:f,n)for(;k<=n;k+=1)m=""===l[k]?g.length:l[k],g=g[m]=k<n?g[m]||(l[k+1]&&isNaN(l[k+1])?{}:[]):f;else e.l(d[m])?d[m].push(f):d[m]=void 0!==d[m]?[d[m],f]:f;else m&&(d[m]=void 0)}return d}},g={O:!1,info:e.s,error:e.log,j:function(){window[b.u]&&(this.O=!0,window[b.u][b.info]&&
(this[b.info]=window[b.u][b.info]),window[b.u][b.error]&&(this[b.error]=window[b.u][b.error]))},reset:function(){this.O=!1;this[b.info]=e.s;this[b.info]=e.log},Mc:function(a){var d=document.createElement(b.Ba);d.src=e.P()+b.N+b.fa+a.message;d.setAttribute(b.width,b.Xa);document.body?document.body.appendChild(d):document.head.appendChild(d)},hb:function(a){a===b.info?(this[b.info]=e.log,this[b.error]=e.log):a===b.error?(this[b.info]=e.s,this[b.error]=e.log):(this[b.info]=e.s,this[b.error]=e.s)}},r=
{J:0,ja:{x:0,y:0},Ka:!0,j:function(){function a(){h.Ka=document[f]?!1:!0}function d(){h.flush();window.removeEventListener("DOMContentLoaded",d,!1)}function c(){/loaded|interactive|complete/.test(document.readyState)&&(document.detachEvent("onreadystatechange",c),g&&(g=!1,h.flush()))}var h=this;h.J=0;this.Va(window,"mousemove",function(a){h.ja={x:a.clientX,y:a.clientY}});if(typeof document.hidden!==b.c){var f="hidden";var e="visibilitychange"}else typeof document.mozHidden!==b.c?(f="mozHidden",e=
"mozvisibilitychange"):typeof document.msHidden!==b.c?(f="msHidden",e="msvisibilitychange"):typeof document.webkitHidden!==b.c&&(f="webkitHidden",e="webkitvisibilitychange");typeof document.addEventListener!==b.c&&typeof f!==b.c&&document.addEventListener(e,a,!1);var g=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",d,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},Sb:function(a,d){var c=document.createElement("iframe"),e=document.body;c.setAttribute("name",
"spr");c.src=a;c.setAttribute("height","1");c.setAttribute("width","1");c.setAttribute("visible","false");c.setAttribute("id","spr-iframe-"+d);c.style.display="none";e||(e=this.f("BODY")[0]);e||(e=this.f("HEAD")[0]);g[b.info](a);e.appendChild(c);return c},na:function(){return this.a(this,b.b,b.Ua)},ma:function(){return this.ua(this,b.ha)},pa:function(){return this.a(this,b.name,b.qb)},ra:function(){return window.location.protocol+b.lb+window.location.hostname+window.location.pathname},qa:function(){var a=
this.ma()||this.na()||this.pa()||this.ra();return e.l(a)?a[0]:a},kc:function(){var a=this.a(this,b.b,b.ea)||this.a(this,b.name,b.V)||this.a(this,b.b,b.V)||this.a(this,b.b,b.ba)||this.a(this,b.b,b.ca)||this.a(this,b.b,b.Ya)||this.va(this,b.La,b.ka)||this.a(this,b.name,b.h);return e.l(a)?a[0]:a},jc:function(){return this.a(this,b.b,b.da)||this.a(this,b.b,b.aa)||this.a(this,b.b,b.K)||this.a(this,b.name,b.K)},ic:function(a,d){return this.a(this,b.b,a)||this.a(this,b.b,d)},xa:function(){return document.referrer},
oa:function(a){a=this.a(this,b.b,b.Ta)||this.a(this,b.name,b.pb)||document.title||a||!1;return e.l(a)?a[0]:a},D:function(a,b,c,e,f){a=a.f(b);b=[];for(var d=0;d<a.length;d++)a[d].getAttribute(c)===e&&b.push(a[d].getAttribute(f));if(b.length)return 1==b.length?b[0]:b},ua:function(a,d){return this.D(a,b.link,b.rel,d,b.href)},a:function(a,d,c){return this.D(a,b.Qa,d,c,b.content)},va:function(a,d,c){return this.D(a,b.time,d,c,b.la)},Gc:function(a){var b=document.body,c=this.f("BODY")[0],e=this.f("HEAD")[0];
b&&b.contains(a)?b.removeChild(a):c&&c.contains(a)?c.removeChild(a):e&&e.contains(a)&&e.removeChild(a);return a},$:function(a){var d=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id","spr-script");c.src=a;g[b.info](a);this.Wa(function(){setTimeout(function(){d.f("HEAD")[0].appendChild(c)},1)});return c},m:[],ready:/loaded|interactive|complete/.test(document.readyState),flush:function(){var a=this.m.shift();
for(this.ready=!0;a;)a(),a=this.m.shift()},Wa:function(a){/loaded|interactive|complete/.test(document.readyState)?(this.m.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function c(){if(!document.uniqueID&&document.expando)return this.m.push(a);try{document.documentElement.doScroll("left"),a()}catch(h){setTimeout(c,0)}}():this.m.push(a):this.m.push(a)},Va:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},Sa:function(a,
b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},Kc:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.J},f:function(a){var b=[],c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(document.getElementById(a.substring(1)));break;case ".":var f=document.getElementsByTagName("*");for(e=" "+a.substring(1)+" ";c<f.length;c+=1)a=(" "+f[c].className+" ").replace(/[\n\t\r]/g,
" "),-1<a.indexOf(e)&&b.push(f[c]);break;default:b=document.getElementsByTagName(a)}return b}},t={callbacks:{},L:b.global,gb:function(a){this.L=a},S:function(a,d,c,h,f){h=h||function(){};f||(f="cb");var g="cb"+e.Za(),p=this;c[f]=this.L+".API.callbacks."+g;f=e.P();"file://"===f&&(f="http://");c[b.tb]=b.version;c=x.encode(c);var k=r.$(f+a+d+"?"+c);p.callbacks[g]=function(a){setTimeout(function(){k.parentNode&&k.parentNode.removeChild(k)},0);h(a);try{delete p.callbacks[g]}catch(n){p.callbacks[g]=null}}}},
u={current:{}},y={U:{},za:function(a){var b=document.cookie||"",c=this.U[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.U[a]=c);return(a=b.match(c))&&decodeURIComponent(a[1])},ib:function(a,b,c){var d="";c&&(d="; expires="+c.toGMTString());document.cookie=a+"="+b+d+"; path=/"},hc:function(a){this.ib(a,"",new Date(1982,5,13))}},w={ga:function(a){var d;var c=e.jb(a);c[b.A]&&(c[b.A]=e.C(c[b.A]));c[b.B]&&(c[b.B]=e.C(c[b.B]));c[b.I]&&(c[b.I]=
e.C(c[b.I]));c[b.h]&&typeof c[b.h]!==b.H&&(c[b.h]=c[b.h].toString());c[b.referrer]=""==c[b.G]?"":this.X(c[b.referrer]);c[b.G]=this.X(c[b.G]);c[b.T]=c[b.T]||window.location.toString();c[b.uid]?c[b.uid]=c[b.uid]:(d=this.ya())&&(c[b.uid]=d);c[b.url]&&(c[b.url]=this.$a(c[b.url]),a[b.url]=c[b.url]);return c},X:function(a){""!==a&&(a=a||r.xa());return a},ya:function(){return y.za(b.sb)},$a:function(a){if(0===a.indexOf("http%253A")||0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||
0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},q=[b.v,b.Fb,b.Ma,b.h],z={create:function(a,b){return new v(a,b)},j:function(a,b){return this.create(a,b).j()}};return{video:function(a){return z.j(a)},debug:g,setLogLevel:function(a){g.hb(a)},API:t}}();window.SimplereachVideo;
